### ISSUE TITLE
RangeRingUtilsTestCase.py fails on list sort tests

### ISSUE THREAD

**Issue by mfunk** [Esri/military-tools-geoprocessing-toolbox#110]
The two tests in _./utils/tests/distance_tests/RangeRingUtilsTestCase.py_ are failing for both Desktop and Pro (tests are EXACTLY the same):
- test_RingMaker_sortList_empty 
- test_RingMaker_sortList_isSorted

```
RESULTS =================================================

Number of tests run: 24
Number of errors: 2
Number of failures: 5

ERRORS =================================================

test_RingMaker_sortList_empty (distance_tests.RangeRingUtilsTestCase.RangeRingUtilsTestCase)Traceback (most recent call last):
  File "D:\GitHub\military-tools-geoprocessing-toolbox\utils\test\distance_tests\RangeRingUtilsTestCase.py", line 102, in test_RingMaker_sortList_empty
    outList = RangeRingUtils.RingMaker._sortList([])
TypeError: unbound method _sortList() must be called with RingMaker instance as first argument (got list instance instead)

..............................................................
test_RingMaker_sortList_isSorted (distance_tests.RangeRingUtilsTestCase.RangeRingUtilsTestCase)Traceback (most recent call last):
  File "D:\GitHub\military-tools-geoprocessing-toolbox\utils\test\distance_tests\RangeRingUtilsTestCase.py", line 113, in test_RingMaker_sortList_isSorted
    outList = RangeRingUtils.RingMaker._sortList(listToSort)
TypeError: unbound method _sortList() must be called with RingMaker instance as first argument (got list instance instead)

..............................................................
```

Both test are failing with the following error:

```
TypeError: unbound method _sortList() must be called with RingMaker instance as first argument (got list instance instead)
```

The line for calling these are similar and are called like this:

```
outList = RangeRingUtils.RingMaker._sortList([])
```

Not getting this with other test methods. Perhaps this is because they are psesudo-internal "private" methods for this module?

**Comment by csmoore** [comment]
The error message seems to make sense: need to create an instance of the class - like you do [here](https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/dev/utils/test/distance_tests/RangeRingUtilsTestCase.py#L85) before calling the methods (unless it is a static method)
