### ISSUE TITLE
test_table_to_twopointline fails with error for Desktop and Pro

### ISSUE THREAD

**Issue by mfunk** [Esri/military-tools-geoprocessing-toolbox#117]
SUMMARY:
- test_table_to_twopointline_pro fails with:
  _ERROR 000628: Cannot set input into parameter Spatial_Reference._
  This suggests that the order of the parameters in the model has changed and should be investigated as a problem in the toolbox.
- test_table_to_twopointline_desktop fails with the following error:
  _ERROR 000728: Field POINT_X does not exist within table_
  _The operation was attempted on an empty geometry._

This seems to be a problem in the model. Not sure if it has anything to do with the recent problems with invalid tool models in the toolboxes.

---

The dialog for Pro is below:

```
test_table_to_twopointline_pro (conversion_tests.TableToTwoPointLineTestCase.TableToTwoPointLineTestCase)Traceback (most recent call last):
  File "D:\GitHub\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToTwoPointLineTestCase.py", line 91, in test_table_to_twopointline_pro
    arcpy.TableTo2PointLine_mt(self.inputTable, "#", "POINT_X", "POINT_Y", "#", "POINT_X2", "POINT_Y2", self.outputLines)
arcgisscripting.ExecuteError: ERROR 000622: Failed to execute (Table To 2-Point Line). Parameters are not valid.
ERROR 000628: Cannot set input into parameter Spatial_Reference.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHub\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToTwoPointLineTestCase.py", line 100, in test_table_to_twopointline_pro
    self.fail(runToolMessage + "\n" + arcpy.GetMessages())
AssertionError: .....TableToTwoPointLineTestCase.test_table_to_twopointline_pro
ERROR 000622: Failed to execute (Table To 2-Point Line). Parameters are not valid.
ERROR 000628: Cannot set input into parameter Spatial_Reference.
```

The full dialog of the test for Desktop is below:

```
test_table_to_twopointline_desktop (conversion_tests.TableToTwoPointLineTestCase.TableToTwoPointLineTestCase)Traceback (most recent call last):
  File "D:\GitHub\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToTwoPointLineTestCase.py", line 80, in test_table_to_twopointline_desktop
    self.fail(runToolMessage + "\n" + arcpy.GetMessages())
AssertionError: .....TableToTwoPointLineTestCase.test_table_to_twopointline_desktop
Executing: TableTo2PointLine D:\GitHub\military-tools-geoprocessing-toolbox\testdata\CSV\TableTo2PointLine.csv DD_2 POINT_X POINT_Y DD_2 POINT_X2 POINT_Y2 D:\GitHub\military-tools-geoprocessing-toolbox\testdata\scratch.gdb\output2PointLines GEODESIC "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119521E-09;0.001;0.001;IsHighPrecision"
Start Time: Mon Jun 06 07:19:46 2016
Executing (Copy Rows): CopyRows D:\GitHub\military-tools-geoprocessing-toolbox\testdata\CSV\TableTo2PointLine.csv C:\Users\<user>\AppData\Local\Temp\scratch.gdb\intermed1 #
Start Time: Mon Jun 06 07:19:47 2016
Succeeded at Mon Jun 06 07:19:47 2016 (Elapsed Time: 0.50 seconds)
Executing (Add Unique Row ID): AddUniqueRowID C:\Users\<user>\AppData\Local\Temp\scratch.gdb\intermed1 JoinID
Start Time: Mon Jun 06 07:19:48 2016
Running script AddUniqueRowID...
Inside AddUniqueRowID.py
Adding field JoinID
Adding unique row IDs
Completed script AddUniqueRowID...
Succeeded at Mon Jun 06 07:19:48 2016 (Elapsed Time: 0.42 seconds)
Executing (Convert Coordinate Notation): ConvertCoordinateNotation C:\Users\<user>\AppData\Local\Temp\scratch.gdb\intermed1 C:\Users\<user>\AppData\Local\Temp\scratch.gdb\intermed2 POINT_X POINT_Y DD_2 DD_2 # "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119521E-09;0.001;0.001;IsHighPrecision" GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]
Start Time: Mon Jun 06 07:19:48 2016
ERROR 000728: Field POINT_X does not exist within table
The operation was attempted on an empty geometry.
Failed to execute (Convert Coordinate Notation).
Failed at Mon Jun 06 07:19:48 2016 (Elapsed Time: 0.40 seconds)
Failed to execute (TableTo2PointLine).
Failed at Mon Jun 06 07:19:49 2016 (Elapsed Time: 2.41 seconds)
```

**Comment by mfunk** [comment]
Fixed in #146
