### ISSUE TITLE
Pro 2.1 Unit Test Exceptions/Errors

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-geoprocessing-toolbox#249]
There are a number of unit test exceptions when running the unit test harness in Pro 2.1 (2.1.9168). These errors seems to be new and do not show when running on Pro 1.4 (though these same test failures do also occur on Pro 1.4). 

The cause of these new failures/exceptions should be investigated.

## Steps to Reproduce (for bugs)

1. On Pro 2.1
2. Run Units Test Driver/Harness (ArcGISProTestKickStart.bat)
3. Note Errors/Exceptions below

## Your Environment

Current Dev branch
Pro 2.1 Beta 1 (2.1.9865)
Windows 10

```
RESULTS =================================================

Number of tests run: 71
Number of errors: 4
Number of failures: 29

ERRORS =================================================

test_findLocalPeaks (visibility_tests.VisibilityUtilitiesTestCase.VisibilityUtilitiesTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Work\Github\military-tools-geoprocessing-toolbox\utils\test\visibility_tests\VisibilityUtilitiesTestCase.py", line 334, in test_findLocalPeaks
    compareResults = arcpy.FeatureCompare_management(resultPoints, expectedLocalPeaks, "OBJECTID").getOutput(1)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 649, in FeatureCompare
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 646, in FeatureCompare
    retval = convertArcObjectToPythonObject(gp.FeatureCompare_management(*gp_fixargs((in_base_features, in_test_features, sort_field, compare_type, ignore_options, xy_tolerance, m_tolerance, z_tolerance, attribute_tolerances, omit_field, continue_compare, out_compare_file), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 506, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000735: Input Base Features: Value is required
Failed to execute (FeatureCompare).


..............................................................
test_findLocalPeaks (visibility_tests.VisibilityUtilitiesTestCase.VisibilityUtilitiesTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Work\Github\military-tools-geoprocessing-toolbox\utils\test\visibility_tests\VisibilityUtilitiesTestCase.py", line 84, in tearDown
    if arcpy.Exists(i):
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 836, in Exists
    return gp.exists(dataset)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 303, in exists
    self._gp.Exists(*gp_fixargs(args, True)))
AttributeError: Object: Error in parsing arguments for Exists

..............................................................
test_find_local_peaks_pro (visibility_tests.FindLocalPeaksTestCase.FindLocalPeaksTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Work\Github\military-tools-geoprocessing-toolbox\utils\test\visibility_tests\FindLocalPeaksTestCase.py", line 90, in test_find_local_peaks_pro
    arcpy.FindLocalPeaks_mt(self.inputArea, 10, self.inputSurface, self.outputPoints)
  File "C:\MyFiles\Work\Github\military-tools-geoprocessing-toolbox\toolboxes\Military_Tools_pro.tbx", line 644, in FindLocalPeaks
    8M/Aev8Axf8AGM3xS+Jc39oajd7TZWbRlIY4lJMaRxkny4U3HYmSSSzsWZmZvoSkVQqhVGAOABS1
  File "C:\MyFiles\Work\Github\military-tools-geoprocessing-toolbox\toolboxes\Military_Tools_pro.tbx", line 641, in FindLocalPeaks
    UUAFFFFABRRRQAV5t+0B8ctK/Z/+H0niTUbSfUrmadbHTtOgypurpkd0RpMERJtjdmdgcKh2h3Ko
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 506, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: Start Time: Monday, October 2, 2017 11:14:20 AM
Distributing operation across 4 parallel instances.
ERROR 999999: Error executing function.
Failed to execute (FlowDirection).
Failed at Monday, October 2, 2017 11:14:23 AM (Elapsed Time: 3.68 seconds)
Failed to execute (FindLocalPeaks).


..............................................................
test_linear_line_of_sight_pro (visibility_tests.LinearLineOfSightTestCase.LinearLineOfSightTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Work\Github\military-tools-geoprocessing-toolbox\utils\test\visibility_tests\LinearLineOfSightTestCase.py", line 133, in test_linear_line_of_sight_pro
    self.outputTargets)
  File "C:\MyFiles\Work\Github\military-tools-geoprocessing-toolbox\toolboxes\Military_Tools_pro.tbx", line 722, in LinearLineOfSight
    7MpNSV0FFFFSMKKKKACs3V/DWla8m3UdOt7wdMyxgkfQ9RWlRTUnF3Qmk9Geaan8BdDlm+0aVc3m
  File "C:\MyFiles\Work\Github\military-tools-geoprocessing-toolbox\toolboxes\Military_Tools_pro.tbx", line 719, in LinearLineOfSight
    3g/miH8zntXTWdnBp9rHb20SQQRjakcYwqj2FS0USlzaLRBGNtXuFFFFZlhRRRQAUUUUARXlpDf2
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 506, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: PYTHON ERRORS:
Traceback info:
  File "C:\MyFiles\Work\Github\military-tools-geoprocessing-toolbox\toolboxes\scripts\VisibilityUtilities.py", line 656, in makeProfileGraph
    arcpy.SetParameter(1,inputFeatures)

Error Info:
Object: Error in setting parameter
ArcPy ERRORS:
Start Time: Monday, October 2, 2017 11:16:53 AM
Succeeded at Monday, October 2, 2017 11:16:54 AM (Elapsed Time: 0.33 seconds)

Failed to execute (LinearLineOfSight).
```

**Comment by csmoore** [comment]
These seems to be all running successfully as of 2.1.10195

```
DEBUG: 2017-11-29 16:43:25,867 UnitTestUtilities - setUpLogFileHeader
INFO: 2017-11-29 16:43:25,867 ------------ Begin Tests ------------------
INFO: 2017-11-29 16:43:25,936 Platform: Windows-10-10.0.15063-SP0
INFO: 2017-11-29 16:43:25,936 Python Version 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]
INFO: 2017-11-29 16:43:25,936 Product: ArcGISPro, Version: 2.1, Installed on: 11/28/2017, Build: 10195.
INFO: 2017-11-29 16:43:25,936 -------------------------------------------
```
...
```
RESULTS =================================================
Number of tests run: 72
Number succeeded: 72
Number of errors: 0
Number of failures: 0
Number of tests skipped: 0
Percent passing: 100.0
=========================================================

INFO: 2017-11-29 16:56:57,428 END OF TEST =========================================
```
