### ISSUE TITLE
Pro 1.4 Unit Test failures - 31 of 71

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-geoprocessing-toolbox#250]
Running the test harness on Pro 1.4 shows a high failure rate (31 of 71 tests ~ 40%) so just creating an issue to track.

## Steps to Reproduce (for bugs)

1. On Pro 1.4
2. Run Units Test Driver/Harness (ArcGISProTestKickStart.bat)
3. Note Failures below

## Your Environment

* Version used:
Current Dev branch
Pro 1.4
Windows 10

```
RESULTS =================================================

Number of tests run: 71
Number of errors: 0
Number of failures: 31

FAILURES ===============================================

test_table_to_ellipse_pro (conversion_tests.TableToEllipseTestCase.TableToEllipseTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToEllipseTestCase.py", line 174, in test_table_to_elli
pse_pro
    self.assertEqual(identical, "true", "Feature Compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature Compare failed:
 Start Time: Monday, October 02, 2017 11:38:30 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:38:30 AM (Elapsed Time: 0.31 seconds)

..............................................................
test_table_to_ellipse_pro_GARS (conversion_tests.TableToEllipseTestCase.TableToEllipseTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToEllipseTestCase.py", line 190, in test_table_to_elli
pse_pro_GARS
    self.assertEqual(identical, "true", "Feature Compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature Compare failed:
 Start Time: Monday, October 02, 2017 11:38:50 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:38:50 AM (Elapsed Time: 0.13 seconds)

..............................................................
test_table_to_ellipse_pro_GEOREF (conversion_tests.TableToEllipseTestCase.TableToEllipseTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToEllipseTestCase.py", line 206, in test_table_to_elli
pse_pro_GEOREF
    self.assertEqual(identical, "true", "Feature Compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature Compare failed:
 Start Time: Monday, October 02, 2017 11:39:10 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:39:11 AM (Elapsed Time: 0.20 seconds)

..............................................................
test_table_to_ellipse_pro_USNG (conversion_tests.TableToEllipseTestCase.TableToEllipseTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToEllipseTestCase.py", line 222, in test_table_to_elli
pse_pro_USNG
    self.assertEqual(identical, "true", "Feature Compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature Compare failed:
 Start Time: Monday, October 02, 2017 11:39:30 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:39:30 AM (Elapsed Time: 0.13 seconds)

..............................................................
test_table_to_ellipse_pro_MGRS (conversion_tests.TableToEllipseTestCase.TableToEllipseTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToEllipseTestCase.py", line 238, in test_table_to_elli
pse_pro_MGRS
    self.assertEqual(identical, "true", "Feature Compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature Compare failed:
 Start Time: Monday, October 02, 2017 11:39:50 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:39:50 AM (Elapsed Time: 0.13 seconds)

..............................................................
test_table_to_ellipse_pro_UTM_BANDS (conversion_tests.TableToEllipseTestCase.TableToEllipseTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToEllipseTestCase.py", line 254, in test_table_to_elli
pse_pro_UTM_BANDS
    self.assertEqual(identical, "true", "Feature Compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature Compare failed:
 Start Time: Monday, October 02, 2017 11:40:10 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:40:10 AM (Elapsed Time: 0.13 seconds)

..............................................................
test_table_to_lineofbearing_pro (conversion_tests.TableToLineOfBearingTestCase.TableToLineOfBearingTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToLineOfBearingTestCase.py", line 181, in test_table_t
o_lineofbearing_pro
    self.assertEqual(identical, "true", "Feature compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature compare failed:
 Start Time: Monday, October 02, 2017 11:40:24 AM
Table: Tables have different number of fields (Base: 15, Test: 13).
GeometryDef: GeometryDef grid size 1 does not match (Base: 0.024000000000, Test: 0.000000000000).
Field: Field Distance_1 aliases are different (Base: Distance_1, Test: Distance).
Field: Field Orientation_1 aliases are different (Base: Orientation_1, Test: Orientation).
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
FeatureClass: Feature class extents are the same.
Succeeded at Monday, October 02, 2017 11:40:25 AM (Elapsed Time: 0.16 seconds)

..............................................................
test_table_to_lineofbearing_pro_MGRS (conversion_tests.TableToLineOfBearingTestCase.TableToLineOfBearingTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToLineOfBearingTestCase.py", line 197, in test_table_t
o_lineofbearing_pro_MGRS
    self.assertEqual(identical, "true", "Feature compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature compare failed:
 Start Time: Monday, October 02, 2017 11:40:40 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:40:40 AM (Elapsed Time: 0.13 seconds)

..............................................................
test_table_to_lineofbearing_pro_GARS (conversion_tests.TableToLineOfBearingTestCase.TableToLineOfBearingTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToLineOfBearingTestCase.py", line 213, in test_table_t
o_lineofbearing_pro_GARS
    self.assertEqual(identical, "true", "Feature compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature compare failed:
 Start Time: Monday, October 02, 2017 11:40:55 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:40:55 AM (Elapsed Time: 0.13 seconds)

..............................................................
test_table_to_lineofbearing_pro_GEOREF (conversion_tests.TableToLineOfBearingTestCase.TableToLineOfBearingTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToLineOfBearingTestCase.py", line 229, in test_table_t
o_lineofbearing_pro_GEOREF
    self.assertEqual(identical, "true", "Feature compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature compare failed:
 Start Time: Monday, October 02, 2017 11:41:10 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:41:10 AM (Elapsed Time: 0.14 seconds)

..............................................................
test_table_to_lineofbearing_pro_USNG (conversion_tests.TableToLineOfBearingTestCase.TableToLineOfBearingTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToLineOfBearingTestCase.py", line 245, in test_table_t
o_lineofbearing_pro_USNG
    self.assertEqual(identical, "true", "Feature compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature compare failed:
 Start Time: Monday, October 02, 2017 11:41:25 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:41:25 AM (Elapsed Time: 0.16 seconds)

..............................................................
test_table_to_lineofbearing_pro_UTM_BANDS (conversion_tests.TableToLineOfBearingTestCase.TableToLineOfBearingTestCase)Traceback (most recent call last
):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToLineOfBearingTestCase.py", line 261, in test_table_t
o_lineofbearing_pro_UTM_BANDS
    self.assertEqual(identical, "true", "Feature compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature compare failed:
 Start Time: Monday, October 02, 2017 11:41:40 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:41:40 AM (Elapsed Time: 0.13 seconds)

..............................................................
test_table_to_point_pro (conversion_tests.TableToPointTestCase.TableToPointTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToPointTestCase.py", line 176, in test_table_to_point_
pro
    self.assertEqual(pointCount, expectedFeatures, "Expected %s features, but got %s" % (str(expectedFeatures), str(pointCount)))
AssertionError: 1000 != 288 : Expected 288 features, but got 1000

..............................................................
test_table_to_point_pro_MGRS (conversion_tests.TableToPointTestCase.TableToPointTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToPointTestCase.py", line 192, in test_table_to_point_
pro_MGRS
    self.assertEqual(pointCount, expectedFeatures, "Expected %s features, but got %s" % (str(expectedFeatures), str(pointCount)))
AssertionError: 1000 != 288 : Expected 288 features, but got 1000

..............................................................
test_table_to_point_pro_GARS (conversion_tests.TableToPointTestCase.TableToPointTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToPointTestCase.py", line 208, in test_table_to_point_
pro_GARS
    self.assertEqual(pointCount, expectedFeatures, "Expected %s features, but got %s" % (str(expectedFeatures), str(pointCount)))
AssertionError: 1000 != 288 : Expected 288 features, but got 1000

..............................................................
test_table_to_point_pro_GEOREF (conversion_tests.TableToPointTestCase.TableToPointTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToPointTestCase.py", line 224, in test_table_to_point_
pro_GEOREF
    self.assertEqual(pointCount, expectedFeatures, "Expected %s features, but got %s" % (str(expectedFeatures), str(pointCount)))
AssertionError: 1000 != 288 : Expected 288 features, but got 1000

..............................................................
test_table_to_point_pro_USNG (conversion_tests.TableToPointTestCase.TableToPointTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToPointTestCase.py", line 240, in test_table_to_point_
pro_USNG
    self.assertEqual(pointCount, expectedFeatures, "Expected %s features, but got %s" % (str(expectedFeatures), str(pointCount)))
AssertionError: 1000 != 288 : Expected 288 features, but got 1000

..............................................................
test_table_to_point_pro_UTM_BANDS (conversion_tests.TableToPointTestCase.TableToPointTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToPointTestCase.py", line 256, in test_table_to_point_
pro_UTM_BANDS
    self.assertEqual(pointCount, expectedFeatures, "Expected %s features, but got %s" % (str(expectedFeatures), str(pointCount)))
AssertionError: 1000 != 288 : Expected 288 features, but got 1000

..............................................................
test_table_to_polyline_pro (conversion_tests.TableToPolylineTestCase.TableToPolylineTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToPolylineTestCase.py", line 178, in test_table_to_pol
yline_pro
    self.assertEqual(identical, "true", "Feature compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature compare failed:
 Start Time: Monday, October 02, 2017 11:44:20 AM
FeatureClass: ObjectID 1 is different for Field Shape (Base: Geometry, Test: Geometry).
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
FeatureClass: Feature class extents are the same.
GeometryDef: GeometryDefs are the same.
Field: Field properties are the same.
Table: Table row counts are the same.
SpatialReference: Spatial references are the same.
Succeeded at Monday, October 02, 2017 11:44:21 AM (Elapsed Time: 0.46 seconds)

..............................................................
test_table_to_polyline_pro_MGRS (conversion_tests.TableToPolylineTestCase.TableToPolylineTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToPolylineTestCase.py", line 194, in test_table_to_pol
yline_pro_MGRS
    self.assertEqual(identical, "true", "Feature compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature compare failed:
 Start Time: Monday, October 02, 2017 11:44:37 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:44:37 AM (Elapsed Time: 0.13 seconds)

..............................................................
test_table_to_polyline_pro_GARS (conversion_tests.TableToPolylineTestCase.TableToPolylineTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToPolylineTestCase.py", line 210, in test_table_to_pol
yline_pro_GARS
    self.assertEqual(identical, "true", "Feature compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature compare failed:
 Start Time: Monday, October 02, 2017 11:44:53 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:44:53 AM (Elapsed Time: 0.13 seconds)

..............................................................
test_table_to_polyline_pro_GEOREF (conversion_tests.TableToPolylineTestCase.TableToPolylineTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToPolylineTestCase.py", line 226, in test_table_to_pol
yline_pro_GEOREF
    self.assertEqual(identical, "true", "Feature compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature compare failed:
 Start Time: Monday, October 02, 2017 11:45:09 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:45:09 AM (Elapsed Time: 0.13 seconds)

..............................................................
test_table_to_polyline_pro_USNG (conversion_tests.TableToPolylineTestCase.TableToPolylineTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToPolylineTestCase.py", line 242, in test_table_to_pol
yline_pro_USNG
    self.assertEqual(identical, "true", "Feature compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature compare failed:
 Start Time: Monday, October 02, 2017 11:45:25 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:45:25 AM (Elapsed Time: 0.14 seconds)

..............................................................
test_table_to_polyline_pro_UTM_BANDS (conversion_tests.TableToPolylineTestCase.TableToPolylineTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToPolylineTestCase.py", line 258, in test_table_to_pol
yline_pro_UTM_BANDS
    self.assertEqual(identical, "true", "Feature compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature compare failed:
 Start Time: Monday, October 02, 2017 11:45:41 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:45:41 AM (Elapsed Time: 0.17 seconds)

..............................................................
test__getFieldNameList (visibility_tests.VisibilityUtilitiesTestCase.VisibilityUtilitiesTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\visibility_tests\VisibilityUtilitiesTestCase.py", line 108, in test__getFiel
dNameList
    self.assertEqual(expectedNames, resultNames, "Did not get expected field names. Got {0} instead.".format(str(resultNames)))
AssertionError: Lists differ: ['ObjectID', 'D1', 'T2'] != ['OBJECTID', 'D1', 'T2']

First differing element 0:
'ObjectID'
'OBJECTID'

- ['ObjectID', 'D1', 'T2']
?    ^^^^^

+ ['OBJECTID', 'D1', 'T2']
?    ^^^^^
 : Did not get expected field names. Got ['OBJECTID', 'D1', 'T2'] instead.

..............................................................
test__getCentroid_FromPoints (visibility_tests.VisibilityUtilitiesTestCase.VisibilityUtilitiesTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\visibility_tests\VisibilityUtilitiesTestCase.py", line 257, in test__getCent
roid_FromPoints
    self.assertEqual(comparePoint.X, resultPoint.X, "Unexpected centroid X. Expected {0}, but got {1}".format(comparePoint.X, resultPoint.X))
AssertionError: 1.0 != 1.0000000000000568 : Unexpected centroid X. Expected 1.0, but got 1.0000000000000568

..............................................................
test__getLocalWAZED (visibility_tests.VisibilityUtilitiesTestCase.VisibilityUtilitiesTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\visibility_tests\VisibilityUtilitiesTestCase.py", line 273, in test__getLoca
lWAZED
    self.assertIs(resultSR, self.srWAZED, "Compare expected Spatial Reference {0} with result {1} failed.".format(self.srWAZED, resultSR))
AssertionError: <SpatialReference object at 0x193111660b8[0x193115f7cf0]> is not <SpatialReference object at 0x193111668d0[0x193115f7eb0]> : Compare e
xpected Spatial Reference <geoprocessing spatial reference object object at 0x00000193115F7EB0> with result <geoprocessing spatial reference object ob
ject at 0x00000193115F7CF0> failed.

..............................................................
test_hi_lowPointByArea_lowest (visibility_tests.VisibilityUtilitiesTestCase.VisibilityUtilitiesTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\visibility_tests\VisibilityUtilitiesTestCase.py", line 297, in test_hi_lowPo
intByArea_lowest
    self.assertEqual(compareResults, "true", "Feature Compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature Compare failed:
 Start Time: Monday, October 02, 2017 11:47:42 AM
GeometryDef: GeometryDef grid size 1 does not match (Base: 1792.341946935691, Test: 1792.341946935479).
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
FeatureClass: Feature class extents are the same.
Field: Field properties are the same.
Succeeded at Monday, October 02, 2017 11:47:42 AM (Elapsed Time: 0.13 seconds)

..............................................................
test_findLocalPeaks (visibility_tests.VisibilityUtilitiesTestCase.VisibilityUtilitiesTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\visibility_tests\VisibilityUtilitiesTestCase.py", line 335, in test_findLoca
lPeaks
    self.assertEqual(compareResults, "true", "Feature Compare failed: \n %s" % arcpy.GetMessages())
AssertionError: 'false' != 'true'
- false
+ true
 : Feature Compare failed:
 Start Time: Monday, October 02, 2017 11:48:55 AM
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Monday, October 02, 2017 11:48:55 AM (Elapsed Time: 0.14 seconds)

..............................................................
test_linear_line_of_sight_pro (visibility_tests.LinearLineOfSightTestCase.LinearLineOfSightTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\visibility_tests\LinearLineOfSightTestCase.py", line 147, in test_linear_lin
e_of_sight_pro
    "Expected {0} observers but got {1}".format(expectedObserverCount, actualObserverCount))
AssertionError: 4 != 16 : Expected 4 observers but got 16

..............................................................
test_radial_line_of_sight_pro (visibility_tests.RadialLineOfSightTestCase.RadialLineOfSightTestCase)Traceback (most recent call last):
  File "C:\MyFiles\Github\military-tools-geoprocessing-toolbox\utils\test\visibility_tests\RadialLineOfSightTestCase.py", line 91, in test_radial_line
_of_sight_pro
    self.assertEqual(featureCount, expectedFeatures, "Expected %s features, but got %s" % (str(expectedFeatures), str(featureCount)))
AssertionError: 623 != 3501 : Expected 3501 features, but got 623

..............................................................

END OF TEST =========================================
```

**Comment by csmoore** [comment]
This is now down to 3 failures due to some precision errors in the 6th decimal place in the tabletoXXX tools so need to make some final enhancements - we are also seeing this precision issue on 10.6 so this should help there also

```
RESULTS =================================================
Number of tests run: 72
Number succeeded: 69
Number of errors: 0
Number of failures: 3
Number of tests skipped: 0
Percent passing: 95.8
=========================================================

ERROR: 2017-11-07 09:05:11,776 FAILURES ================================================
ERROR: 2017-11-07 09:05:11,777 test_table_to_lineofbearing (conversion_tests.TableToLineOfBearingTestCase.TableToLineOfBearingTestCase)
ERROR: 2017-11-07 09:05:11,777 Traceback (most recent call last):
ERROR: 2017-11-07 09:05:11,777   File "c:\jenkins\TestPipeline2\workspace\utils\test\conversion_tests\TableToLineOfBearingTestCase.py", line 105, in test_table_to_lineofbearing
ERROR: 2017-11-07 09:05:11,777     "OID", 0.0001, ['Shape_Length'])
ERROR: 2017-11-07 09:05:11,777   File "c:\jenkins\TestPipeline2\workspace\utils\test\arcpyAssert.py", line 123, in assertFeatureClassEqualSimple
ERROR: 2017-11-07 09:05:11,777     None, None, None, omit_field)
ERROR: 2017-11-07 09:05:11,777   File "c:\jenkins\TestPipeline2\workspace\utils\test\arcpyAssert.py", line 111, in assertFeatureClassEqual
ERROR: 2017-11-07 09:05:11,777     raise AssertionError(msg)
ERROR: 2017-11-07 09:05:11,777 AssertionError: Feature class c:\jenkins\TestPipeline2\workspace\utils\test\scratch.gdb\outputLines is not equal to c:\jenkins\TestPipeline2\workspace\testdata\Results.gdb\ExpectedOutputTableToLOB
ERROR: 2017-11-07 09:05:11,778 test_table_to_point (conversion_tests.TableToPointTestCase.TableToPointTestCase)
ERROR: 2017-11-07 09:05:11,778 Traceback (most recent call last):
ERROR: 2017-11-07 09:05:11,778   File "c:\jenkins\TestPipeline2\workspace\utils\test\conversion_tests\TableToPointTestCase.py", line 104, in test_table_to_point
ERROR: 2017-11-07 09:05:11,778     "OID", 0.0001)
ERROR: 2017-11-07 09:05:11,778   File "c:\jenkins\TestPipeline2\workspace\utils\test\arcpyAssert.py", line 123, in assertFeatureClassEqualSimple
ERROR: 2017-11-07 09:05:11,778     None, None, None, omit_field)
ERROR: 2017-11-07 09:05:11,778   File "c:\jenkins\TestPipeline2\workspace\utils\test\arcpyAssert.py", line 111, in assertFeatureClassEqual
ERROR: 2017-11-07 09:05:11,778     raise AssertionError(msg)
ERROR: 2017-11-07 09:05:11,778 AssertionError: Feature class c:\jenkins\TestPipeline2\workspace\utils\test\scratch.gdb\outputTableToPoint is not equal to c:\jenkins\TestPipeline2\workspace\testdata\Results.gdb\ExpectedOutputTableToPoint
ERROR: 2017-11-07 09:05:11,779 test_hi_lowPointByArea_lowest (visibility_tests.VisibilityUtilitiesTestCase.VisibilityUtilitiesTestCase)
ERROR: 2017-11-07 09:05:11,779 Traceback (most recent call last):
ERROR: 2017-11-07 09:05:11,779   File "c:\jenkins\TestPipeline2\workspace\utils\test\visibility_tests\VisibilityUtilitiesTestCase.py", line 316, in test_hi_lowPointByArea_lowest
ERROR: 2017-11-07 09:05:11,779     "OBJECTID", 0.0001)
ERROR: 2017-11-07 09:05:11,779   File "c:\jenkins\TestPipeline2\workspace\utils\test\arcpyAssert.py", line 123, in assertFeatureClassEqualSimple
ERROR: 2017-11-07 09:05:11,779     None, None, None, omit_field)
ERROR: 2017-11-07 09:05:11,779   File "c:\jenkins\TestPipeline2\workspace\utils\test\arcpyAssert.py", line 111, in assertFeatureClassEqual
ERROR: 2017-11-07 09:05:11,780     raise AssertionError(msg)
ERROR: 2017-11-07 09:05:11,780 AssertionError: Feature class c:\jenkins\TestPipeline2\workspace\testdata\Results.gdb\ExpectedOutputLowestPt is not equal to c:\jenkins\TestPipeline2\workspace\utils\test\scratch.gdb\lowestPoints
INFO: 2017-11-07 09:05:11,780 END OF TEST =========================================
```

**Comment by csmoore** [comment]
This is ready to verify on all versions except Pro 2.1 ( #260 )

**Comment by ACueva** [comment]
Verified.
![2017-11-17_13-26-37](https://user-images.githubusercontent.com/3093940/32969708-f602dd8e-cb9a-11e7-8546-9e417e551eea.png)
