### ISSUE TITLE
Add GRG tools to Military Tools .pyt

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-geoprocessing-toolbox#276]
Issue https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/262 has been broken down

GRG

- [X] CreateGRGFromArea
- [X] CreateGRGFromPoint
- [X] CreateReferenceSystemGRGFromArea

Acceptance Criteria:
Target release: Military Tools 3.0
One toolbox
Tests written and running for tools
Tools documented
User documentation complete and published
Tested
Toolbox included in the .zip

**Comment by lfunkhouser** [comment]
@csmoore has completed the dev on the tools. I am unsure of status of the remaining tasks - doc, testing, Jenkins running tests with pass/fail output...

**Comment by csmoore** [comment]
That is a good reminder - we haven't yet copied/moved the unit tests from https://github.com/Esri/solutions-geoprocessing-toolbox/tree/dev/utils/test/clearing_operations_tests to this repo so that work still needs done

**Comment by csmoore** [comment]
Test migrated from https://github.com/Esri/solutions-geoprocessing-toolbox/tree/dev/utils/test/clearing_operations_tests to this repo in PR #288

**Comment by ACueva** [comment]
@csmoore GRG unit tests run successfully on the ArcGIS Pro 2.1 Build.

Still having issues with GRG on ArcMap 10.3.1.

```
INFO: 2018-05-10 15:08:46,838 Test success: False
INFO: 2018-05-10 15:08:46,838 
RESULTS =================================================
Number of tests run: 86
Number succeeded: 80
Number of errors: 6
Number of failures: 0
Number of tests skipped: 0
Percent passing: 0.0
=========================================================

ERROR: 2018-05-10 15:08:46,838 ERRORS ==================================================
ERROR: 2018-05-10 15:08:46,838 testCreateReferenceSystemGRGFromArea_1000M (grg_tests.GRGCreateReferenceSystemGRGFromAreaTestCase.GRGCreateReferenceSystemGRGFromAreaTestCase)
ERROR: 2018-05-10 15:08:46,838 Traceback (most recent call last):
ERROR: 2018-05-10 15:08:46,839   File "c:\jDev\workspace\GP Unit tests\ArcMap Test Runner\military-tools-geoprocessing-toolbox\utils\test\grg_tests\GRGCreateReferenceSystemGRGFromAreaTestCase.py", line 266, in testCreateReferenceSystemGRGFromArea_1000M
ERROR: 2018-05-10 15:08:46,839     self.xy_tolerance)
ERROR: 2018-05-10 15:08:46,839   File "c:\jDev\workspace\GP Unit tests\ArcMap Test Runner\military-tools-geoprocessing-toolbox\utils\test\arcpyAssert.py", line 93, in assertFeatureClassEqual
ERROR: 2018-05-10 15:08:46,839     out_compare_file=compare_file[1])
ERROR: 2018-05-10 15:08:46,839   File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcPy\arcpy\management.py", line 410, in FeatureCompare
ERROR: 2018-05-10 15:08:46,841     raise e
ERROR: 2018-05-10 15:08:46,841 ExecuteError: Failed to execute. Parameters are not valid.
ERROR: 2018-05-10 15:08:46,841 ERROR 000800: The value is not a member of IGNORE_M | IGNORE_Z | IGNORE_POINTID | IGNORE_EXTENSION_PROPERTIES | IGNORE_SUBTYPES | IGNORE_RELATIONSHIPCLASSES | IGNORE_REPRESENTATIONCLASSES.
ERROR: 2018-05-10 15:08:46,841 Failed to execute (FeatureCompare).
ERROR: 2018-05-10 15:08:46,841 testCreateReferenceSystemGRGFromArea_100KM (grg_tests.GRGCreateReferenceSystemGRGFromAreaTestCase.GRGCreateReferenceSystemGRGFromAreaTestCase)
ERROR: 2018-05-10 15:08:46,841 Traceback (most recent call last):
ERROR: 2018-05-10 15:08:46,842   File "c:\jDev\workspace\GP Unit tests\ArcMap Test Runner\military-tools-geoprocessing-toolbox\utils\test\grg_tests\GRGCreateReferenceSystemGRGFromAreaTestCase.py", line 176, in testCreateReferenceSystemGRGFromArea_100KM
ERROR: 2018-05-10 15:08:46,842     self.xy_tolerance)
ERROR: 2018-05-10 15:08:46,842   File "c:\jDev\workspace\GP Unit tests\ArcMap Test Runner\military-tools-geoprocessing-toolbox\utils\test\arcpyAssert.py", line 93, in assertFeatureClassEqual
ERROR: 2018-05-10 15:08:46,842     out_compare_file=compare_file[1])
ERROR: 2018-05-10 15:08:46,842   File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcPy\arcpy\management.py", line 410, in FeatureCompare
ERROR: 2018-05-10 15:08:46,842     raise e
ERROR: 2018-05-10 15:08:46,842 ExecuteError: Failed to execute. Parameters are not valid.
ERROR: 2018-05-10 15:08:46,842 ERROR 000800: The value is not a member of IGNORE_M | IGNORE_Z | IGNORE_POINTID | IGNORE_EXTENSION_PROPERTIES | IGNORE_SUBTYPES | IGNORE_RELATIONSHIPCLASSES | IGNORE_REPRESENTATIONCLASSES.
ERROR: 2018-05-10 15:08:46,842 Failed to execute (FeatureCompare).
ERROR: 2018-05-10 15:08:46,842 testCreateReferenceSystemGRGFromArea_100M (grg_tests.GRGCreateReferenceSystemGRGFromAreaTestCase.GRGCreateReferenceSystemGRGFromAreaTestCase)
ERROR: 2018-05-10 15:08:46,842 Traceback (most recent call last):
ERROR: 2018-05-10 15:08:46,842   File "c:\jDev\workspace\GP Unit tests\ArcMap Test Runner\military-tools-geoprocessing-toolbox\utils\test\grg_tests\GRGCreateReferenceSystemGRGFromAreaTestCase.py", line 311, in testCreateReferenceSystemGRGFromArea_100M
ERROR: 2018-05-10 15:08:46,842     self.xy_tolerance)
ERROR: 2018-05-10 15:08:46,842   File "c:\jDev\workspace\GP Unit tests\ArcMap Test Runner\military-tools-geoprocessing-toolbox\utils\test\arcpyAssert.py", line 93, in assertFeatureClassEqual
ERROR: 2018-05-10 15:08:46,842     out_compare_file=compare_file[1])
ERROR: 2018-05-10 15:08:46,842   File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcPy\arcpy\management.py", line 410, in FeatureCompare
ERROR: 2018-05-10 15:08:46,842     raise e
ERROR: 2018-05-10 15:08:46,842 ExecuteError: Failed to execute. Parameters are not valid.
ERROR: 2018-05-10 15:08:46,844 ERROR 000800: The value is not a member of IGNORE_M | IGNORE_Z | IGNORE_POINTID | IGNORE_EXTENSION_PROPERTIES | IGNORE_SUBTYPES | IGNORE_RELATIONSHIPCLASSES | IGNORE_REPRESENTATIONCLASSES.
ERROR: 2018-05-10 15:08:46,844 Failed to execute (FeatureCompare).
ERROR: 2018-05-10 15:08:46,844 testCreateReferenceSystemGRGFromArea_10KM (grg_tests.GRGCreateReferenceSystemGRGFromAreaTestCase.GRGCreateReferenceSystemGRGFromAreaTestCase)
ERROR: 2018-05-10 15:08:46,844 Traceback (most recent call last):
ERROR: 2018-05-10 15:08:46,844   File "c:\jDev\workspace\GP Unit tests\ArcMap Test Runner\military-tools-geoprocessing-toolbox\utils\test\grg_tests\GRGCreateReferenceSystemGRGFromAreaTestCase.py", line 221, in testCreateReferenceSystemGRGFromArea_10KM
ERROR: 2018-05-10 15:08:46,844     self.xy_tolerance)
ERROR: 2018-05-10 15:08:46,844   File "c:\jDev\workspace\GP Unit tests\ArcMap Test Runner\military-tools-geoprocessing-toolbox\utils\test\arcpyAssert.py", line 93, in assertFeatureClassEqual
ERROR: 2018-05-10 15:08:46,845     out_compare_file=compare_file[1])
ERROR: 2018-05-10 15:08:46,845   File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcPy\arcpy\management.py", line 410, in FeatureCompare
ERROR: 2018-05-10 15:08:46,845     raise e
ERROR: 2018-05-10 15:08:46,845 ExecuteError: Failed to execute. Parameters are not valid.
ERROR: 2018-05-10 15:08:46,845 ERROR 000800: The value is not a member of IGNORE_M | IGNORE_Z | IGNORE_POINTID | IGNORE_EXTENSION_PROPERTIES | IGNORE_SUBTYPES | IGNORE_RELATIONSHIPCLASSES | IGNORE_REPRESENTATIONCLASSES.
ERROR: 2018-05-10 15:08:46,845 Failed to execute (FeatureCompare).
ERROR: 2018-05-10 15:08:46,845 testCreateReferenceSystemGRGFromArea_10M (grg_tests.GRGCreateReferenceSystemGRGFromAreaTestCase.GRGCreateReferenceSystemGRGFromAreaTestCase)
ERROR: 2018-05-10 15:08:46,845 Traceback (most recent call last):
ERROR: 2018-05-10 15:08:46,845   File "c:\jDev\workspace\GP Unit tests\ArcMap Test Runner\military-tools-geoprocessing-toolbox\utils\test\grg_tests\GRGCreateReferenceSystemGRGFromAreaTestCase.py", line 356, in testCreateReferenceSystemGRGFromArea_10M
ERROR: 2018-05-10 15:08:46,845     self.xy_tolerance)
ERROR: 2018-05-10 15:08:46,845   File "c:\jDev\workspace\GP Unit tests\ArcMap Test Runner\military-tools-geoprocessing-toolbox\utils\test\arcpyAssert.py", line 93, in assertFeatureClassEqual
ERROR: 2018-05-10 15:08:46,845     out_compare_file=compare_file[1])
ERROR: 2018-05-10 15:08:46,845   File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcPy\arcpy\management.py", line 410, in FeatureCompare
ERROR: 2018-05-10 15:08:46,846     raise e
ERROR: 2018-05-10 15:08:46,846 ExecuteError: Failed to execute. Parameters are not valid.
ERROR: 2018-05-10 15:08:46,846 ERROR 000800: The value is not a member of IGNORE_M | IGNORE_Z | IGNORE_POINTID | IGNORE_EXTENSION_PROPERTIES | IGNORE_SUBTYPES | IGNORE_RELATIONSHIPCLASSES | IGNORE_REPRESENTATIONCLASSES.
ERROR: 2018-05-10 15:08:46,846 Failed to execute (FeatureCompare).
ERROR: 2018-05-10 15:08:46,846 testCreateReferenceSystemGRGFromArea_GZD (grg_tests.GRGCreateReferenceSystemGRGFromAreaTestCase.GRGCreateReferenceSystemGRGFromAreaTestCase)
ERROR: 2018-05-10 15:08:46,846 Traceback (most recent call last):
ERROR: 2018-05-10 15:08:46,846   File "c:\jDev\workspace\GP Unit tests\ArcMap Test Runner\military-tools-geoprocessing-toolbox\utils\test\grg_tests\GRGCreateReferenceSystemGRGFromAreaTestCase.py", line 131, in testCreateReferenceSystemGRGFromArea_GZD
ERROR: 2018-05-10 15:08:46,846     self.xy_tolerance)
ERROR: 2018-05-10 15:08:46,846   File "c:\jDev\workspace\GP Unit tests\ArcMap Test Runner\military-tools-geoprocessing-toolbox\utils\test\arcpyAssert.py", line 93, in assertFeatureClassEqual
ERROR: 2018-05-10 15:08:46,848     out_compare_file=compare_file[1])
ERROR: 2018-05-10 15:08:46,848   File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcPy\arcpy\management.py", line 410, in FeatureCompare
ERROR: 2018-05-10 15:08:46,848     raise e
ERROR: 2018-05-10 15:08:46,848 ExecuteError: Failed to execute. Parameters are not valid.
ERROR: 2018-05-10 15:08:46,848 ERROR 000800: The value is not a member of IGNORE_M | IGNORE_Z | IGNORE_POINTID | IGNORE_EXTENSION_PROPERTIES | IGNORE_SUBTYPES | IGNORE_RELATIONSHIPCLASSES | IGNORE_REPRESENTATIONCLASSES.
ERROR: 2018-05-10 15:08:46,848 Failed to execute (FeatureCompare).
INFO: 2018-05-10 15:08:46,848 END OF TEST =========================================
'One or more tests failed'
Build step 'Execute Windows batch command' marked build as failure
Finished: FAILURE
```
Full logs can be found here:
http://StagingServer:8080/job/GP%20Unit%20tests/job/ArcMap%20Test%20Runner/34/console

**Comment by lfunkhouser** [comment]
Test design is available here for GRG from area, https://github.com/Esri/military-tools-geoprocessing-toolbox/wiki/GRG-From-Area. Test can be written.

**Comment by csmoore** [comment]
Moving to In Progress to work on implementing the unit test design ( https://github.com/Esri/military-tools-geoprocessing-toolbox/wiki/GRG-From-Area#grg-from-area ) - some of the work was started in #295 so working in that branch

**Comment by dfoll** [comment]
Removing G - Doc (CMS) verified what is in the .pyt for Gridded Reference Graphic matches what is in the Gridded Reference Graphic toolset documentation

**Comment by csmoore** [comment]
Finished auto test design and implementation for CreateReferenceSystemGRGFromArea at:

1. Design: https://github.com/Esri/military-tools-geoprocessing-toolbox/wiki/GRG-CreateReferenceSystemGRGFromArea
2. Code changes in branch: https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/csm/%23276-update-unit-tests-per-design

Moving on to start on GRG-From-Point [test design](https://github.com/Esri/military-tools-geoprocessing-toolbox/wiki/GRG-From-Point)

**Comment by csmoore** [comment]
GRG-From-Point automated test design and implementation added at:

1. Test design: https://github.com/Esri/military-tools-geoprocessing-toolbox/wiki/GRG-From-Point
2. Implementation: PR #304
